/**
 * Created by Administrator on 2017/12/12.
 */

export const ACTIONS_DEL_SHOPPINGCAR = 'ACTIONS_DEL_SHOPPINGCAR'
export const ACTIONS_ADD_SHOPPINGCAR = 'ACTIONS_ADD_SHOPPINGCAR'

export const MUTATIONS_DEL_SHOPPINGCAR = 'MUTATIONS_DEL_SHOPPINGCAR'
export const MUTATIONS_ADD_SHOPPINGCAR = 'MUTATIONS_ADD_SHOPPINGCAR'
